name: Format Code

on:
  push:
    branches:
      - next
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ['3.8']

    steps:
    - name: Setup Python
      uses: actions/setup-python@v2.2.2
      with:
        python-version: 3.8
        architecture: x64

    - name: Install poetry and dependencies
      run: |
        python -m pip install --upgrade pip poetry
        python -m poetry install

    - name: Format with black via poetry scripts
      run: |
        poetry run fmt
